### ISSUE TITLE
Image View - allocation failed for scaled bitmap

### ISSUE THREAD

**Issue by bethgrace5** [codeherlife/Melaniemills#1]
Image is too large. It crashes application.

```
Throwing OutOfMemoryError "Failed to allocate a 864000012 byte allocation with 4362194 free bytes and 249MB until OOM"
--- allocation failed for scaled bitmap
Shutting down VM

FATAL EXCEPTION: main
                                                   Process: com.codeherlife.melaniemills, PID: 17704
                                                   java.lang.OutOfMemoryError: Failed to allocate a 864000012 byte allocation with 4362194 free bytes and 249MB until OOM
                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                       at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
                                                       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
                                                       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1179)
                                                       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:770)
                                                       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
                                                       at android.content.res.Resources.getDrawable(Resources.java:1640)
                                                       at android.content.Context.getDrawable(Context.java:525)
                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:351)
                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                       at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:58)
                                                       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
                                                       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
                                                       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                       at com.codeherlife.melaniemills.MainActivity.onCreate(MainActivity.java:16)
                                                       at android.app.Activity.performCreate(Activity.java:6912)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```
![screen shot 2018-02-19 at 2 18 55 am](https://user-images.githubusercontent.com/4492670/36373057-c7aa4920-151b-11e8-8e63-691e0de83693.png)

**Comment by bethgrace5** [comment]
Otherwise, commenting out the image view, and modifying the ArrayAdapter to use the correct views, it works!

```
         ArrayAdapter<String> adapter = new ArrayAdapter<String>(
                 this,
                 R.layout.list_item_candy,
                 R.id.text_view_candy,
                 events_list);
```
![screenshot_20180219-022521](https://user-images.githubusercontent.com/4492670/36373286-843206a0-151c-11e8-9375-c2a499f3ef8b.png)
